### ISSUE TITLE
Loading tweets failed with Uncaught ReferenceError: twttr is not defined when using Firefox

### ISSUE THREAD

**Issue by billmetangmo** [medialab/catwalk#5]
Hello,

Thanks for this awesome tool.
I tried to use it on Firefox latest version ( 104.0.2) but it failed when loading the sample csv with the below error:

![image](https://user-images.githubusercontent.com/25366207/190676569-0c3811ec-af01-4c83-8321-1aba9c3ad9da.png)

Work as expected on Google chrome .

**Comment by Yomguithereal** [comment]
I think it may be because of tracking protection that is on by default on firefox and shunts twitter, instagram, facebook widgets and iframes. Can you try clicking on the shield icon left to the url and disable the protection for the app and see if this fixes it (an adblocker could also be it)?

**Comment by billmetangmo** [comment]
Yes you are right. I disabled it and it works.
Thank you very much.

**Comment by boogheta** [comment]
Thanks for the report, I added a notice to the user in such case for others!
